services:
  mpi-master:
    build: .
    container_name: mpi-master
    hostname: mpi-master
    networks:
      mpi_net:
        ipv4_address: 172.20.0.2
    environment:
      - HOSTS=mpi-master,mpi-worker1,mpi-worker2,mpi-worker3,mpi-worker4
    volumes:
      - ./src:/root/work
    depends_on:
      - mpi-worker1
      - mpi-worker2
      - mpi-worker3
      - mpi-worker4

  mpi-worker1:
    build: .
    container_name: mpi-worker1
    hostname: mpi-worker1
    networks:
      mpi_net:
        ipv4_address: 172.20.0.3
    volumes:
      - ./src:/root/work

  mpi-worker2:
    build: .
    container_name: mpi-worker2
    hostname: mpi-worker2
    networks:
      mpi_net:
        ipv4_address: 172.20.0.4
    volumes:
      - ./src:/root/work

  mpi-worker3:
    build: .
    container_name: mpi-worker3
    hostname: mpi-worker3
    networks:
      mpi_net:
        ipv4_address: 172.20.0.5
    volumes:
      - ./src:/root/work

  mpi-worker4:
    build: .
    container_name: mpi-worker4
    hostname: mpi-worker4
    networks:
      mpi_net:
        ipv4_address: 172.20.0.6
    volumes:
      - ./src:/root/work

networks:
  mpi_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
